name: uncold_ai_moc
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^10.0.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  gap: ^3.0.1
  http: ^1.3.0
  google_sign_in: ^6.3.0
  googleapis: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
